### ISSUE TITLE
underline styling is not proper wrt design

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#100]
underline styling is not proper wrt design
web:
![image](https://user-images.githubusercontent.com/4660706/130018626-91368756-ac32-4a9b-a257-530f361ce01e.png)

design:
![image](https://user-images.githubusercontent.com/4660706/130018650-741ba36b-db45-4bec-a22a-301ffb9c08f4.png)

**Comment by georgioajency** [comment]
Ignore
