### ISSUE TITLE
spacing after images looks less as compared to design

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#101]
spacing after images looks less as compared to design:

web:
![image](https://user-images.githubusercontent.com/4660706/130018837-5d9ecea4-ccb7-49b5-8e23-d0997c1f3699.png)

**Comment by georgioajency** [comment]
@chaitanya-ajency please increase this by a few pixels. Now that I look at it, it does seem less. 
Sorry for the change.

**Comment by snehaajency** [comment]
fixed
