### ISSUE TITLE
alignment of double quotes image should be slightly lower

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#105]
alignment of double quotes image should be slightly lower

web:
![image](https://user-images.githubusercontent.com/4660706/130019817-246ecf99-4eb0-4bad-98e5-59b7ca3a6461.png)

design:
![image](https://user-images.githubusercontent.com/4660706/130019879-6696769c-3cfe-4010-8ff4-9cfe4eadc05b.png)

**Comment by georgioajency** [comment]
Updated the icons. Pick them from here. 
https://www.figma.com/file/B5YrdRm2j8WfdcM75ipMyc/Cibil---CC?node-id=551%3A1086
Low priority. Do this once everything else is fixed.

**Comment by snehaajency** [comment]
fixed
