### ISSUE TITLE
font weight  looks more at most of the places

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#107]
font weight  looks more at most of the places
![image](https://user-images.githubusercontent.com/4660706/130022292-b4dbd0da-2b88-4a34-8b40-4f8f6e218f2c.png)
![image](https://user-images.githubusercontent.com/4660706/130022404-3c18499f-1518-414c-b3ac-29c059c8d159.png)
![image](https://user-images.githubusercontent.com/4660706/130022487-a7a6aadb-6be3-4d42-a124-71deed1f15e2.png)

**Comment by georgioajency** [comment]
Ignore.
