### ISSUE TITLE
Issues seen for email-3

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#12]
**case**: 

1. the icon used for 3rd card is not matching design
web:
![image](https://user-images.githubusercontent.com/4660706/122760832-2e26a780-d2b9-11eb-9635-b070bf3c13aa.png)
expected:
![image](https://user-images.githubusercontent.com/4660706/122760861-3848a600-d2b9-11eb-8506-cdae70f0b6d9.png)

2 icons look blur, instagram icon missing
![image](https://user-images.githubusercontent.com/4660706/122761261-aa20ef80-d2b9-11eb-9acb-4394b60ab10d.png)

3.Blur logo

4.information for good logo is blur
5.click here in footer doesnt work

**Comment by Vaibhavarolkar** [comment]
Instagram icon missing =>
@snehaajency 
![image](https://user-images.githubusercontent.com/52398680/122880618-d25f2b80-d357-11eb-89b2-4b341ac858ec.png)

**Comment by Vaibhavarolkar** [comment]
All the logo's re taken from design.
@georgioajency need better quality images.

**Comment by Vaibhavarolkar** [comment]
5.click here in footer doesnt work => @georgioajency

**Comment by snehaajency** [comment]
fixed
