### ISSUE TITLE
Gmail Mobile Issues

### ISSUE THREAD

**Issue by georgioajency** [ajency/CIBIL-CRO#121]
![IMG_20210820_115328](https://user-images.githubusercontent.com/43877959/130189584-03bd95a5-3511-469d-987c-21d219cc2414.jpg)

1. Increase padding. Also full stop after Subscription.
2. Current plan not aligned to dashes
3. Text should be CIBIL Subscription.  
4. This entire section the text looks big and cramped. Can it be made neater?
5. Can the width of the emailer go edge to edge on mobile?
6. Spelling mistake. Health.

**Comment by Vaibhavarolkar** [comment]
point 4 - Not possible

**Comment by Vaibhavarolkar** [comment]
point 5 - Not possible.

**Comment by snehaajency** [comment]
As informed by developer this ticket is not needed anymore.
