### ISSUE TITLE
space above footer is more

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#126]
![image](https://user-images.githubusercontent.com/4660706/131495687-f008afb3-8529-48dc-a603-c680f1cdccfc.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency please keep it according to design
![image](https://user-images.githubusercontent.com/4660706/131508806-cb98a8fd-da05-4e05-a78f-f116872d96bf.png)
figma:
![image](https://user-images.githubusercontent.com/4660706/131508838-4b79c22f-9fdc-4173-a89a-9f20c3df9bf9.png)

**Comment by chaitanya-ajency** [comment]
Hard refresh
