### ISSUE TITLE
dash inside the box are not properly aligned

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#128]
dash inside the box are not properly aligned
![image](https://user-images.githubusercontent.com/4660706/131496305-c3003676-97c4-4d59-b07f-454040735b3c.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency keep it verticaly centre,also button text doesnt look verticaly centre

**Comment by snehaajency** [comment]
@chaitanya-ajency replicates
![image](https://user-images.githubusercontent.com/4660706/132175200-a17df02b-645b-4907-8e0c-d064e41dfd78.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 09 06-12_48_28 (1)](https://user-images.githubusercontent.com/79827708/132176164-10e8339e-fadb-4141-9d1b-756ec65ae1ad.png)
