### ISSUE TITLE
the mobile image should come between blue and white section

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#13]
**case**:the mobile image should come between blue and white section
![image](https://user-images.githubusercontent.com/4660706/122762335-d8eb9580-d2ba-11eb-9873-25e67d53b6b3.png)

client:yahoo,outlook

**Comment by Vaibhavarolkar** [comment]
Have used icons from design.
Need better images.
@snehaajency @georgioajency

**Comment by Vaibhavarolkar** [comment]
This will not work in either of rediff or outlook.
If we use gradient it won't work in outlook and if we use it will work in outlook but wont work in rediff.
rediff changes the tags to ba-ckground from background 
![image](https://user-images.githubusercontent.com/52398680/122908263-8e792000-d371-11eb-9c10-0b48acbc1cb4.png)
@georgioajency

**Comment by georgioajency** [comment]
Outlook is important. Handle it for outlook.

**Comment by snehaajency** [comment]
@georgioajency @Vaibhavarolkar the above issue is fixed for outlook.
currently on rediff mail the blue backgrond and the text on it cant be seen
image:
![image](https://user-images.githubusercontent.com/4660706/122912606-1eb96400-d376-11eb-9abe-39dd429e05cc.png)

**Comment by HazelColaco19** [comment]
@Vaibhavarolkar It looks very bad in rediff, can we try something here?
