### ISSUE TITLE
mobile:otp box issue

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#131]
1. the otp boxes edges doesnt match with design
2. "resend otp" placment should be right below the last otp box

web:
![image](https://user-images.githubusercontent.com/4660706/131497664-12a0c559-9587-4403-88c7-df27f6a1196a.png)

design:
![image](https://user-images.githubusercontent.com/4660706/131497701-df5d7359-9c34-4763-8029-438d4a0273bf.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency please check point 1

**Comment by chaitanya-ajency** [comment]
Not replicating

**Comment by snehaajency** [comment]
@chaitanya-ajency please attach a screenshot

**Comment by chaitanya-ajency** [comment]
https://ik.imagekit.io/adi1239457/Screenshot_20210901-123051_Chrome_LwcvM_D94.jpg
