### ISSUE TITLE
font family is not matching in design its intro regular,but in web it is "Intro, "Trebuchet MS", Helvetica, Arial, sans-serif;"

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#133]
**case**:" common issue on both pages 
font family is not matching in design its intro regular,but in web it is "Intro, "Trebuchet MS", Helvetica, Arial, sans-serif;"

**Comment by snehaajency** [comment]
@chaitanya-ajency as mentioned issue is seen on otp page aswell,fixed on duplicate.

**Comment by chaitanya-ajency** [comment]
@snehaajency not replicating.. Please do a hard refresh
