### ISSUE TITLE
by default please keep "yes" as selected option

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#143]
by default please keep "yes" as selected option

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 09 06-11_47_00](https://user-images.githubusercontent.com/79827708/132169313-f0759b53-387a-4a69-a778-695ee07e672f.png)

**Comment by chaitanya-ajency** [comment]
Please do a hard refesh
