### ISSUE TITLE
mobile issues for email 3

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#15]
**case**: the icons look blurry on mobile devices
![image](https://user-images.githubusercontent.com/4660706/122765597-4baa4000-d2be-11eb-9418-0fef4cf79958.png)

2 the question mark icon besides 'did you know ' looks blur

3.could  see extra line which is not seen in design fort all cards
![image](https://user-images.githubusercontent.com/4660706/122766398-194d1280-d2bf-11eb-80c2-e1dacf14cb34.png)

**Comment by Vaibhavarolkar** [comment]
Have used icons from design.
Need better images.
@snehaajency @georgioajency

**Comment by Vaibhavarolkar** [comment]
point 3 is fixed

**Comment by georgioajency** [comment]
@snehaajency please add Saiesh and Flinn to Github. Icons can be asked from Saiesh.

**Comment by snehaajency** [comment]
please check point 3 for yahoo( mobile) could replicate

**Comment by snehaajency** [comment]
fixed
