### ISSUE TITLE
mobile :spacing issues

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#154]
case: please consider same points mentioned on #151 for this page aswell
device:ios and android

**Comment by snehaajency** [comment]
@chaitanya-ajency 
please check the spacings after "you can start...." looks more.
check before invoice details box.

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 09 06-11_56_32](https://user-images.githubusercontent.com/79827708/132170292-45ac3469-8c9f-4eff-a598-27a6a02ac319.png)
