### ISSUE TITLE
images are not getting displayed

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#16]
**case**:

1. images not getting displayed
2. blue section is getting cropped.
3. card sizes are not equal

client : android/ios rediff
![image](https://user-images.githubusercontent.com/4660706/122766898-ac864800-d2bf-11eb-8ea5-0bb81a4c1d29.png)
![image](https://user-images.githubusercontent.com/4660706/122769331-1a337380-d2c2-11eb-843f-e7e7561a22d3.png)

**Comment by Vaibhavarolkar** [comment]
There is an option to enable images on mobile.
Enable images all the issues will be fixed.
@snehaajency 
![WhatsApp Image 2021-06-22 at 13 14 21](https://user-images.githubusercontent.com/52398680/122884700-05a3b980-d35c-11eb-85b8-62304b2f94d3.jpeg)

**Comment by snehaajency** [comment]
@Vaibhavarolkar please check point-3 ,occurs on ios device
![image](https://user-images.githubusercontent.com/4660706/122911731-380de080-d375-11eb-92fd-c4dc5660992c.png)

**Comment by snehaajency** [comment]
@Vaibhavarolkar  the icons are too big and card size is not matching
![image](https://user-images.githubusercontent.com/4660706/122916335-6510c200-d37a-11eb-8614-4e534c7015e1.png)

**Comment by snehaajency** [comment]
fixed
