### ISSUE TITLE
card title is wrong,playstore button is not clickable

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#164]
case:

1. title on card is not matching with design,can see "enter your details" as title for testiomnials,
expected:CUSTOMER TESTIMONIALS

2. only 2 carousel can be seen whereas in design can see 3.
3. alignment of carousel should be to the left,its in centre right now
3. playstore button is not clickable.

image:
![image](https://user-images.githubusercontent.com/4660706/131953534-8a30e858-029f-4453-b078-e48e562eb133.png)

design:
https://www.figma.com/file/fjsvu1ewKcND4sVllLBvqM/CIBIL-Design-System-_-EF-UI?node-id=0%3A1

**Comment by chaitanya-ajency** [comment]
Point 2.. There is no content for other slides provided and also they will put whatever they need

**Comment by snehaajency** [comment]
@chaitanya-ajency please fix point 3

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5500-2021 09 06-12_29_48](https://user-images.githubusercontent.com/79827708/132174038-e548750a-27ed-44a7-a9ed-ca37bbfefda4.png)
