### ISSUE TITLE
space besides the "4m+" card on left is less

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#167]
case: space besides the "4m+" card on left is less

image:
![image](https://user-images.githubusercontent.com/4660706/131954534-4b9d8b75-4ac3-44af-adcf-1740b41ba30e.png)

design:
![image](https://user-images.githubusercontent.com/4660706/131954555-9a05ed0f-50e1-4c0b-a926-a2e1953ed984.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency spacing on righ is not matching design.
![image](https://user-images.githubusercontent.com/4660706/132164077-648aeffc-e1f8-42c0-826c-25a26b5cc494.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency issue replicates,spacing on left is reduced

**Comment by snehaajency** [comment]
![image](https://user-images.githubusercontent.com/4660706/132203241-95b6ea0a-27d2-4cb5-863a-ac18f42dd8cc.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5500-2021 09 06-16_15_51](https://user-images.githubusercontent.com/79827708/132205659-1a6e8550-9c23-4e39-a8e1-5f34db784955.png)

**Comment by chaitanya-ajency** [comment]
ui break and design won't meet if given more spacing

**Comment by snehaajency** [comment]
closing this issue due to abve comment by developer
