### ISSUE TITLE
text is not aligned vertically centre

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#189]
text is not aligned vertically centre
![image](https://user-images.githubusercontent.com/4660706/132006406-96424dfd-f9ee-481c-9d61-d75582568d86.png)

**Comment by snehaajency** [comment]
![image](https://user-images.githubusercontent.com/4660706/132168224-31e2654f-d692-4e89-b487-f86c7c63a941.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 09 06-12_57_55](https://user-images.githubusercontent.com/79827708/132177129-4b15cebb-3f88-43c8-b4d2-c4dbc8aa7528.png)
