### ISSUE TITLE
plan title missing 

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#192]
plan title missing 
web:
![image](https://user-images.githubusercontent.com/4660706/132007996-a3f45dd0-be76-4f87-8b07-f48fdc994dac.png)
![image](https://user-images.githubusercontent.com/4660706/132008358-47bca5cf-0577-4939-b92a-11fc4fb7bfc3.png)

design:
![image](https://user-images.githubusercontent.com/4660706/132008039-ae31d9de-9c2d-4e23-8ae4-c6649ceb12ec.png)
![image](https://user-images.githubusercontent.com/4660706/132008372-799f32bd-bcf8-4af8-b4a9-48e881ac1c76.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency please verify if for "6months" and "12months" aswell it should show "free plan"
![image](https://user-images.githubusercontent.com/4660706/132168807-12fb3de4-3549-493a-ac75-8744c649b1ce.png)
![image](https://user-images.githubusercontent.com/4660706/132168825-4044caf4-aa9f-4c50-a8c7-d231feabee17.png)

**Comment by chaitanya-ajency** [comment]
As discussed with Georgio the free plan should remain for all tabs
