### ISSUE TITLE
when you click on each box the box color changes to active state and remains there.

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#194]
when you click on each box the box color changes to active state and remains there.
![image](https://user-images.githubusercontent.com/4660706/132167253-c7694d89-3a56-43f8-b82a-f2e0be3dd660.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 09 06-11_53_57](https://user-images.githubusercontent.com/79827708/132170027-307f0348-fc7a-451b-b7f5-fd4d087135e0.png)

**Comment by chaitanya-ajency** [comment]
Hard refresh

**Comment by snehaajency** [comment]
@chaitanya-ajency 
steps:

https://www.awesomescreenshot.com/video/5115551?key=e792083c8bc82ecaf6a39a98c0fba66f
