### ISSUE TITLE
tick mark is not matching with design

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#209]
tick mark is not matching with design
![image](https://user-images.githubusercontent.com/4660706/132180288-9a7da9d4-20a6-4f65-a52f-915412a24f0c.png)

**design:**

![image](https://user-images.githubusercontent.com/4660706/132180235-55b742fa-6e94-4537-a035-1bc43e1ff438.png)

**Comment by chaitanya-ajency** [comment]
The image is taken from desktop design, which on responsive will use the same
