### ISSUE TITLE
size and color of the cross is not matching

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#224]
expected size:14*14

![image](https://user-images.githubusercontent.com/4660706/132325644-e82ff566-7569-487e-bf0a-3cb84f88237e.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 09 07-17_47_22](https://user-images.githubusercontent.com/79827708/132343128-87939370-8a04-4c8b-bf15-e7b810d12f2b.png)
