### ISSUE TITLE
header and footer is missing

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#233]
header is missing
![image](https://user-images.githubusercontent.com/4660706/133609272-ba906326-fa5b-4cd1-8548-e3c49ce12815.png)
![image](https://user-images.githubusercontent.com/4660706/133614563-d86dea5d-34aa-4487-b613-364ec733ca07.png)

**Comment by chaitanya-ajency** [comment]
Told to exclude
