### ISSUE TITLE
mobile: plan section issues.

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#248]
1. button text in the design is "get started" in web it us "upgrade now"
2. text for 1-month plan is not similar to design text.
3. can see a black border around the button.
4. button width looks less.
5. space after the card end is less.
6. color of ticks is incorrect
![image](https://user-images.githubusercontent.com/4660706/133755897-5f1fdc7b-7f2d-45d4-8980-f6627723616e.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency please check point 2 also the tick size looks less on mobile

**Comment by snehaajency** [comment]
@chaitanya-ajency please match content from Figma if it was sked to keep it that way comment

**Comment by chaitanya-ajency** [comment]
This is the same plan text that from desktop.. only the design here in mobile is changed.. the content is same
