### ISSUE TITLE
the steps number icons look blur

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#257]

**Comment by snehaajency** [comment]
replicates

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5502-2021 09 17-19_23_58](https://user-images.githubusercontent.com/79827708/133794321-30f444d9-d28d-4190-a314-b417c4527039.png)

**Comment by chaitanya-ajency** [comment]
Image taken is 4x from figma
