### ISSUE TITLE
pop is seen in enlarged view, no space seen above and below popup 

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#276]
pop is seen in enlarged view, no space seen above and below popup when screen **resolution is 100%**

![image](https://user-images.githubusercontent.com/4660706/134658314-5145b045-bc93-4b6f-b084-61450bd1cde4.png)

**Comment by chaitanya-ajency** [comment]
Depend on viewport.. The viewport in figma is different.. to reduce the height i will have to reduce the spacing of text

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5502-2021 09 24-16_57_47](https://user-images.githubusercontent.com/79827708/134667227-ce3afb29-a44e-43d2-beee-4811a44a4c87.png)

**Comment by chaitanya-ajency** [comment]
@georgioajency

**Comment by snehaajency** [comment]
closing based on developers comment
