### ISSUE TITLE
in design there was a tooltip shown for 'personized loan offer'.

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#290]
**web:** can see 'free plan...." below the paragraph unlike in design, where there is a tooltip and when you havor on tooltip you can see the message.
![image](https://user-images.githubusercontent.com/4660706/135205796-652bc7be-cc0f-41e7-b715-b082f1af2a9a.png)

**design:**
![image](https://user-images.githubusercontent.com/4660706/135205894-3b52af02-1755-4fad-93ac-1b6ed7575036.png)

**Comment by chaitanya-ajency** [comment]
Not yet told to implement
