### ISSUE TITLE
following text not matching with design 

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#299]
web:marked text is no matching design
![image](https://user-images.githubusercontent.com/4660706/135211077-c9cc5f8c-910a-43b6-b692-a7584c61061c.png)
![image](https://user-images.githubusercontent.com/4660706/135211145-164c4022-24e5-4f30-80e1-7d8a3afd095d.png)
![image](https://user-images.githubusercontent.com/4660706/135211186-c8b5426b-1da6-44df-948a-1bd1c8c03374.png)
![image](https://user-images.githubusercontent.com/4660706/135211292-e7b0ccc6-f3b3-4878-ae92-82a525a293d4.png)
![image](https://user-images.githubusercontent.com/4660706/135211366-f17cff24-9035-4d1b-80c8-b4a71b46256b.png)
![image](https://user-images.githubusercontent.com/4660706/135211465-2b10470e-9820-4899-beaa-f2892c23e62d.png)
![image](https://user-images.githubusercontent.com/4660706/135211955-098dcc34-53a5-467e-9894-ef58266ed331.png)
![image](https://user-images.githubusercontent.com/4660706/135212021-f2a70504-3ab6-4444-8d4b-b642a4980212.png)
![image](https://user-images.githubusercontent.com/4660706/135212182-f8ba5d26-755b-417e-87d6-4e0c71ae4789.png)
![image](https://user-images.githubusercontent.com/4660706/135212549-629aa49f-ac28-4acb-95b1-033b76b8d2d0.png)

**Comment by georgioajency** [comment]
Copy text and position to follow the same as v1
https://www.figma.com/file/ixTFxYHZ7I6G8TxYMo4aaL/Landing-Pages?node-id=205%3A3787
