### ISSUE TITLE
spacing  issues  seen for mobile

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#34]
**device:** ios / android.

**case:** following issues are seen for mobile:
1. The gap is less.
2. Gap is more.
3. the card is overlapped on mobile image on ios 
3. 1. the mobile image is moved to right on android,
**images**
![image](https://user-images.githubusercontent.com/4660706/127267683-21025a54-58fc-4946-80a1-0f9641eb69ea.png)

**Comment by ankitasangodkar** [comment]
2. Gap is more - spacing is given 50px in design
