### ISSUE TITLE
mobile :  phone number field allowing special characters

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#348]
check all fields which should have restrictions on phone they are letting user enter special characters

![image](https://user-images.githubusercontent.com/4660706/136565662-1a2cb71f-e573-4f00-9be5-6bbdbc24040b.png)

**Comment by chaitanya-ajency** [comment]
This issue is not replicating

**Comment by snehaajency** [comment]
@chaitanya-ajency still can add a dot
