### ISSUE TITLE
font styling for active state is not matching

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#358]
please verify if this is a design issue.

seen in design that when a text field is active, the label above becomes bold,rest should have font-family normal.
currently, all the labels are having font bold.
![image](https://user-images.githubusercontent.com/4660706/136737503-de8ed983-5a75-4940-97d4-f7ee8797acda.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency labels are turning bold when you click on label name or beside it
https://www.awesomescreenshot.com/video/5579253?key=f9cc90c1ebfb73ba16258b13179c86f3

**Comment by georgioajency** [comment]
Will check with the designer how this has to be. But yes noticed that once you select a field the label gets bold and continues to remain bold even if you go ahead and select another field. Ideally, this should not be the case. But will confirm.

**Comment by georgioajency** [comment]
Confirmed. The label should be bold when the field is selected and should become non-bold when de-selected
