### ISSUE TITLE
require links for the following on home page:

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#38]
**link**:https://ajency.github.io/CIBIL-CRO/homepage/homepage
require links for the following on home page:

1. under 'help center'
![image](https://user-images.githubusercontent.com/4660706/127270031-f369a216-9bda-46c4-bebd-3902367bade9.png)

2.under 'other queries'
![image](https://user-images.githubusercontent.com/4660706/127270115-01b66c8d-53b8-421b-aeee-6eff648f22c1.png)

3. 
![image](https://user-images.githubusercontent.com/4660706/127270319-31787c03-7be7-47b7-b9f2-632deb9755fd.png)

**Comment by georgioajency** [comment]
1.a
https://www.cibil.com/frequent-queries
https://www.cibil.com/consumer
https://www.cibil.com/loan-approval-process

1b. 
https://www.cibil.com/resources/docs/CIBIL-Report-Understanding.pdf
https://www.cibil.com/resources/docs/MyCIBIL-Understanding.pdf
https://www.cibil.com/resources/docs/understand-your-cibil-company-credit-report.pdf

--------

2
https://myscore.cibil.com/CreditView/enrollShort.page?enterprise=CIBIL&offer=FACR&_gl=1*16xkgp*_ga*NjE3MzQzOTc0LjE2MjQ5NjE3MDA.*_ga_GGL6JJ79K2*MTYyNzQ1MjQzOS44Ny4xLjE2Mjc0NTI3MzAuMA..&_ga=2.204694866.356984845.1627275504-617343974.1624961700
https://www.cibil.com/consumer-dispute-resolution
https://www.cibil.com/kyc-upload
https://www.cibil.com/#

3
https://www.cibil.com/company-credit-report

**Comment by snehaajency** [comment]
@ankitasangodkar please add the above links
