### ISSUE TITLE
popup / when you click on checkbox the arrow touches right side of box

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#435]
![image](https://user-images.githubusercontent.com/4660706/140740598-49d0e8d0-12c2-4ebc-bcb2-079a84d0fa08.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 11 08-18_43_01](https://user-images.githubusercontent.com/79827708/140748071-b41b0456-fe29-4422-80fc-a616f2bfa635.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-ajency github io-2021 11 08-18_44_27](https://user-images.githubusercontent.com/79827708/140748325-9d6beeb6-8aab-4fbf-8757-5a38ded4501d.png)
