### ISSUE TITLE
below marked whole section is clickable 

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#439]
expected: this section should be either non-clickable or only the cards should be clickable

![image](https://user-images.githubusercontent.com/4660706/141051995-c1205885-d8a4-4f76-95b3-318716f3d880.png)

**Comment by chaitanya-ajency** [comment]
Default behaviour, showing its and image

**Comment by snehaajency** [comment]
closing this issue based on developers comment
