### ISSUE TITLE
space on left looks less.

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#45]
space on left looks less.
![image](https://user-images.githubusercontent.com/4660706/127864960-02d0984c-7ddf-4b86-9f0c-94677a3188fe.png)

**Comment by ankitasangodkar** [comment]
Added 34.5px as per [design](https://www.figma.com/file/0mQKUYFiQ8bMbZv4zqFP1z/CIBIL---Signup-Flow?node-id=1577%3A164)
