### ISSUE TITLE
mobile / incorrect text. match it with design

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#488]
![image](https://user-images.githubusercontent.com/4660706/142598752-ab6cfc77-5296-43f8-b0e1-003a3a821a01.png)
![image](https://user-images.githubusercontent.com/4660706/142598834-17080a75-3c66-4e0f-b9b1-302260f0a654.png)

**Comment by chaitanya-ajency** [comment]
Sdud be kept same as desktop
