### ISSUE TITLE
Interstitial popup not opening.

### ISSUE THREAD

**Issue by georgioajency** [ajency/CIBIL-CRO#49]
Popup should open when you click the link
![image](https://user-images.githubusercontent.com/43877959/127870674-a405f3a4-97ac-4f12-b429-2307c7b2b175.png)

Refer original CIBIL site for popup. Need to include popup code.
![image](https://user-images.githubusercontent.com/43877959/127871084-70c31783-b5c7-4687-8d4f-6890af6e0ec4.png)

**Comment by snehaajency** [comment]
it opens in new tab, cant see popup

**Comment by chaitanya-ajency** [comment]
@snehaajency the isssue was to be fixed on main website.. Links needs to be changed while exporting..
