### ISSUE TITLE
mobile / text not matching

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#494]
**the text in design looks like dummy text, please let me know what should be the correct text**

![image](https://user-images.githubusercontent.com/4660706/142605718-f085910f-7785-43cc-806d-4bc1cdc219a0.png)

design:
![image](https://user-images.githubusercontent.com/4660706/142606109-d5526acc-1e86-4997-9bce-5fdc7da5a21e.png)

**Comment by chaitanya-ajency** [comment]
text wont change on mobile.. this will be for all cases as in desktop.. confirmed by Georgio
