### ISSUE TITLE
gap seen above 'most popular' 

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#520]
![image](https://user-images.githubusercontent.com/4660706/143813653-f8d48a26-abc4-4768-b1ad-8913defa21e5.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5503-2021 12 03-13_26_54](https://user-images.githubusercontent.com/79827708/144566290-1cdd5687-9f15-426a-a75c-c6b6834d738d.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency can you verify on smaller devices, this screenshot is taken on device with resolution 1280*720
