### ISSUE TITLE
Little gap is seen beside 'save 75%" label.

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#522]
switch to standard plan to replicate
![image](https://user-images.githubusercontent.com/4660706/143815411-4c1d8a36-decb-49d4-8e87-800b9a6cbf19.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency please check beside 'save 81%' , similar issue is replicating. for above mentioned label it is fixed.

**Comment by chaitanya-ajency** [comment]
![Capture](https://user-images.githubusercontent.com/79827708/145004187-3855ce07-46a5-455b-bf6e-d685abb466bf.PNG)
