### ISSUE TITLE
Gap seen on near corner of 'most popular;'

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#523]
![image](https://user-images.githubusercontent.com/4660706/143817603-2fa8adda-6b89-47d4-a869-4834bdd5c418.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5501-2021 12 07-15_06_49](https://user-images.githubusercontent.com/79827708/145004430-8070f95d-36c2-4b7e-9039-4633289c29c3.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5501-2021 12 07-15_09_16](https://user-images.githubusercontent.com/79827708/145004796-233240c1-6d7b-4192-9d33-85a995537a62.png)
