### ISSUE TITLE
when the search box becomes empty all the fields elements should load again,

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#528]
case: when the search box becomes empty all the fields elements should load again.

steps:
1. type "mmm" inside 'search by bank' 
2. now you will  see 'no results found
3. now backspace it by pressing the backspace continuously 
4. you will notice it and click outside. you will notice data is not getting loaded now still  can see " no results found"

_FYI:_
**this scenario becomes non-replictable if you backspace and stop after each letter.**
https://www.awesomescreenshot.com/video/6205326?key=574ea281388bb3f338ba830c18a3f3b7

**Comment by chaitanya-ajency** [comment]
Not informed to do
