### ISSUE TITLE
on mobie can see buttons of both options (yellow/orange) togther

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#531]
![image](https://user-images.githubusercontent.com/4660706/144967446-6e5d8b5b-7115-46d9-a412-05f98dadbec7.png)
![image](https://user-images.githubusercontent.com/4660706/144967464-0afdfe5a-d908-4c84-a702-c6978964077a.png)

**Comment by chaitanya-ajency** [comment]
https://ajency.github.io/CIBIL-CRO/alerts-landing-page/alerts-landing-page.html
