### ISSUE TITLE
white background for marked area is missing

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#535]
![image](https://user-images.githubusercontent.com/4660706/145169900-9d44f19f-f89c-4972-b0b7-e0e59d858896.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/145169945-a1474bf9-d996-48c9-98ca-93c496baa57e.png)

**Comment by chaitanya-ajency** [comment]
Hard refresh
