### ISSUE TITLE
fontstyling of text 'banner ads' is not according to design

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#539]
![image](https://user-images.githubusercontent.com/4660706/145174042-b044a683-abbc-4718-ba1e-e5380e5ec27b.png)

expected:
//styleName: H4 Bold;
font-family: Intro Bold;
font-size: 16px;
font-style: normal;
font-weight: 700;
line-height: 24px;
letter-spacing: 0.02em;
text-align: left;

**Comment by chaitanya-ajency** [comment]
There will be an ad here.. so can ignore the current styling
