### ISSUE TITLE
wrong button text seen

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#554]
![image](https://user-images.githubusercontent.com/4660706/145359047-ee935ecf-09a3-40ef-9150-bb948ce2f3ca.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/145358756-cbf32b55-24dc-4e0b-aa94-2c4eca5f9212.png)

**Comment by chaitanya-ajency** [comment]
Test should be same as desktop
