### ISSUE TITLE
the text 'add to compare' need to be verticaly center wrt the checkbox

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#563]
![image](https://user-images.githubusercontent.com/4660706/145759548-ac98d86a-87a9-467a-acdd-eaf8b7ee063b.png)

**Comment by chaitanya-ajency** [comment]
![screenshot-127 0 0 1_5500-2021 12 14-15_34_46](https://user-images.githubusercontent.com/79827708/145977095-327fef3e-efc7-4a2b-9078-53b2984c168f.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency 
![image](https://user-images.githubusercontent.com/4660706/145979479-cb01da40-577d-4309-921b-908ddf702c07.png)
