### ISSUE TITLE
Upgrade page - Mobile view

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#625]
**Case:**
The background color for the 6 months and 12 months subscription box is white (#FFFFFF)

**Image:**
![image](https://user-images.githubusercontent.com/96518669/147457374-ed81c3ae-bffb-4b98-9571-a6ba400f3078.png)

**Expected:**
The background color should be: #F9F9F9 with a border color of #ACACAC 
And the premium box should have a corner radius of 6px

**Expected Image:**
![image](https://user-images.githubusercontent.com/96518669/147457819-a9feb2f6-ab59-4aab-b8a8-20cf8db97af1.png)

**Comment by chaitanya-ajency** [comment]
Kept on purpose.. ui breaks if space increased

**Comment by Saee1799** [comment]
Issue is about the background color
