### ISSUE TITLE
Alerts (Free - Desktop) CRA Padding 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#662]
Case:
Padding between the CTA and text is 40px

Image:
![image](https://user-images.githubusercontent.com/96518669/147677287-86ecdf95-e18c-4fcc-86af-875ceea64a9c.png)

Expected:
The padding between the CTA and text should be the following
top padding: 60px, bottom padding with the container: 40px

**Comment by chaitanya-ajency** [comment]
UI wil break
