### ISSUE TITLE
Alerts (Free - 4k Resolution) - Plan container width 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#667]
Case:
At 4k resolution the plan container width is 488px

Image:
![image](https://user-images.githubusercontent.com/96518669/147679127-eea8f683-160f-42bb-9125-70044adf4619.png)

Expected:
The container should be of the following dimension
160x536

**Comment by chaitanya-ajency** [comment]
cannot give fixed width

**Comment by Saee1799** [comment]
okay
