### ISSUE TITLE
My Accounts (Paid) - Subscription tab 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#697]
Case:
Dimensions for the "3Days left" container is 382x234 px

Image:
![image](https://user-images.githubusercontent.com/96518669/147751654-5721a73a-34d7-4c75-a1bf-5b1c1d62f092.png)

Expected:
The "3 days left" container should have the dimensions of 374x215, with a 40px top and bottom padding and 44px left and right padding for the text in the container

Expected design image:
![image](https://user-images.githubusercontent.com/96518669/147751899-df080258-503a-4b5e-ad8e-b73df0587c76.png)

**Comment by chaitanya-ajency** [comment]
cannot apply fixed dimension properties

**Comment by Saee1799** [comment]
okay
