### ISSUE TITLE
My Account (Paid - Subscription tab) - iPad pro resolution - Text spacing 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#700]
### **Case:**
In the iPad pro resolution (1024), the start date and end date text looks crammed 

### **Image:**
![image](https://user-images.githubusercontent.com/96518669/147804388-67d8e820-ebf6-449b-b07f-57e281551ed9.png)

### **Expected:**
The "Start date" text should take only one line.

**Comment by georgioajency** [comment]
Add some spacing between start and end date
