### ISSUE TITLE
Upgrade (Paid- mobile/desktop resolution) - footer links

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#718]
### **Case:**
FAQ link is not clickable on mobile and on hover/press all the links are turning blue

### **Image:**
![image](https://user-images.githubusercontent.com/96518669/147814972-23ef4bd9-0916-478e-a3ce-925192c52460.png)

### **Expected:**
FAQ link should be clickable and on hover/click links should be in #F16E00 color

**Comment by georgioajency** [comment]
Please link this to the existing pages.

FAQ
https://myscore.cibil.com/CreditView/support.page?tab=faq&enterprise=CIBIL

Terms and Conditions
https://myscore.cibil.com/CreditView/support.page?tab=legal&subtab=terms&enterprise=CIBIL

Privacy Policy
https://myscore.cibil.com/CreditView/support.page?tab=legal&subtab=privacy&enterprise=CIBIL
