### ISSUE TITLE
plan section doesnt look proper on mobile 

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#73]
plan section doesnt look proper on mobile 
![image](https://user-images.githubusercontent.com/4660706/128202443-2f754789-8c3d-4f8d-907b-2c9baa776fff.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency keep height of cards equal in mobile view

**Comment by snehaajency** [comment]
@chaitanya-ajency: client yahoo,button is missing
![image](https://user-images.githubusercontent.com/4660706/128294141-2bfe0c99-cc52-42ec-af19-8f3bb030cec3.png)

**Comment by snehaajency** [comment]
@chaitanya-ajency 
the height is unequal 
![image](https://user-images.githubusercontent.com/4660706/128297527-6440a13a-401a-4e14-b6d5-dc02e9d16d47.png)

**Comment by chaitanya-ajency** [comment]
Design changed
