### ISSUE TITLE
Alerts (Paid - Desktop/mobile) - Dashboard breadcrumb leads to a broken page 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#739]
### **Case:**
"Dashboard home" breadcrumb link leads to a broken dashboard page

### **Video:**
https://user-images.githubusercontent.com/96518669/147819104-1c355491-e2f0-4319-8571-e1a6ae55e509.mp4

**Comment by georgioajency** [comment]
@chaitanya-ajency add this link
https://myscore.cibil.com/CreditView/dashboard.page?enterprise=CIBIL
