### ISSUE TITLE
Number of screens and top & bottom arrow color 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#747]
### **Case:**
There are only 2 scroll screen options
The top and bottom arrow color is grey

### **Image:**
![image](https://user-images.githubusercontent.com/96518669/147927392-72e0063b-63db-439a-ae0a-143f62f854c9.png)

### **Expected:**
There should be 4 scroll screens, as there are 4 different features
The top and bottom arrow should be of the following color: #00A6CA

**Comment by chaitanya-ajency** [comment]
I think it should appear on hover?

**Comment by georgioajency** [comment]
@Saee1799 please confirm with Karan

**Comment by Saee1799** [comment]
I'll ask Karan

**Comment by Saee1799** [comment]
Arrows should be in the CIBIL blue color, with no hover effect @chaitanya-ajency
