### ISSUE TITLE
Mobile mockup screen behavior 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#749]
### **Expected behavior:**
When a feature changes, only the right mobile screen will change and will showcase an image which is related to the feature which is being explained. The screen on the left will remain the same (showing the dashboard screenshot)

### **Image:**
![image](https://user-images.githubusercontent.com/96518669/147928619-04fa0055-9882-4893-a8d7-5475b60cc4de.png)

**Comment by chaitanya-ajency** [comment]
Not possible to place the left image on exact position.. it wil kepp changing  position

**Comment by georgioajency** [comment]
Ok. @Saee1799 please inform Karan of the same wrt to technical challange of doing this.

**Comment by Saee1799** [comment]
It is working fine
