### ISSUE TITLE
Clarity for "Download on app store" button

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#753]
### **Case:**
The "Download on app store" button is unclear 

### **Image:**
![image](https://user-images.githubusercontent.com/96518669/147936013-4650dac8-0753-4caa-93d0-cceaeeeb8f17.png)

### **Expected:**
Use SVG and a clear version of the download on app store button

**Comment by chaitanya-ajency** [comment]
It is an svg

**Comment by georgioajency** [comment]
@Saee1799 The icon on design itself is blurry when you scroll in

**Comment by Saee1799** [comment]
okay

**Comment by Saee1799** [comment]
Will try to find a better svg version
