### ISSUE TITLE
alignment if "already have a cibil..." is not according to design

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#76]
alignment if "already have a cibil..." is not according to design
expected: should be centre aligned
image:
![image](https://user-images.githubusercontent.com/4660706/128312762-51dc7105-8026-46e0-a5bc-7dd8e1f9fc5b.png)

**Comment by ankitasangodkar** [comment]
@snehaajency  Georgio had asked to make it left align
