### ISSUE TITLE
Box width - mobile 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#797]
### **Case:**
The control number box's width is longer and the know more about cibil score box's width is smaller  
This is the case for all the tabs except Summary report 

### **Image:**
![image](https://user-images.githubusercontent.com/96518669/148938891-e24dc4c5-e7bd-4f1b-8673-56fec06b882d.png)

### **Expected:**
The control number box should be small and have the Print cibil report box right next to it,
The know more about CIBIL score box's width should be long and have no other container next to it

### **Expected design image:**
![image](https://user-images.githubusercontent.com/96518669/148939261-ceeca508-b109-4a72-9b29-3506c9fd5be3.png)

**Make this change for all the tabs except summary report tab**

**Comment by chaitanya-ajency** [comment]
WHat i have implemented is new changes

**Comment by Saee1799** [comment]
okay @chaitanya-ajency
