### ISSUE TITLE
Score card animation is not updated 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#838]
**CASE:**
The CIBIL Score card animation is not updates (has square edges)

**IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150319659-26dbe531-2ac2-4f39-9739-5745e7691be9.png)

**EXPECTED DESIGN IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150320114-9e7f8b49-9186-4848-9d97-d0d8a44dd8ec.png)

**Comment by siddeshKalangutkar** [comment]
As the meter is displayed using the gauge js library, CSS cannot be applied for making the edges rounded.

**Comment by Saee1799** [comment]
Okay.
