### ISSUE TITLE
Selected tab is grey in color 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#842]
CASE:
The tab in highlight does not have a line on top, and the background color of the number of offers available is grey

IMAGE:
![image](https://user-images.githubusercontent.com/96518669/150328595-8e188819-33bd-4b53-ae65-6628a3f171bb.png)

EXPECTED:
The tab in highlight should have a tab select line on top and the background color of the number of offers available should be blue 

EXPECTED DESIGN IMAGE:
![image](https://user-images.githubusercontent.com/96518669/150328841-b377681b-9d58-4596-bc03-228cf62cc9f0.png)

**Comment by siddeshKalangutkar** [comment]
Styling for the active tab has been added.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
