### ISSUE TITLE
Tabs function is not working 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#843]
**CASE:**
Tabs are not changing on tap

**VIDEO:**
https://user-images.githubusercontent.com/96518669/150329542-758ba192-37c3-49ae-ad07-1e7ea1a117a9.mp4

**EXPECTED:**
Tabs should change on tap

**Comment by siddeshKalangutkar** [comment]
Tab selection functionality has been added.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
