### ISSUE TITLE
Compare button - enabled with two offers for comparison 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#845]
CASE:
Compare button is enabled after selecting two offers for comparison

IMAGE:
![image](https://user-images.githubusercontent.com/96518669/150330465-c0b5ca45-5382-4108-aa04-9516ff1d1a4d.png)

EXPETCED:
Minimum three offers need to be added for comparison, and then the compare button turns into its enabled state

**Comment by georgioajency** [comment]
@ankitasangodkar this is correct. Please change the text to Please add a minimum of 2 offers to compare.
