### ISSUE TITLE
Compare offer - button functionality

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#846]
**CASE:**
When any offers are added to the compare section, and then removed from that section, the compare button stay in its active state

**VIDEO:**
https://user-images.githubusercontent.com/96518669/150331823-95832d96-c200-4c15-ae67-083c3698a89c.mp4

**EXPECTED:**
When offers are take out of the compare state, the Compare button should go into its disabled state

_**The compare button will only be in its enabled state when there are minimum 3 offers to be compared**_

**Comment by siddeshKalangutkar** [comment]
Fix added to disable the compare button if less than 1 offer is added.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
