### ISSUE TITLE
Comparison section, on adding an offer 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#847]
**CASE:**
When an offer is selected for comparison, the compare section appears at the bottom of the page, so the user has to scroll down to check if the offer is added or not 

**VIDEO:**
https://user-images.githubusercontent.com/96518669/150332642-cab2921c-d451-4bd9-9b70-7cb0eb3a5c01.mp4

**EXPECTED:**
The comparison section needs to be sticky.

**Comment by siddeshKalangutkar** [comment]
The comparison section has been made sticky.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
