### ISSUE TITLE
Apply now button function 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#848]
**CASE:**
On clicking the apply button, the terms and conditions popup does not appear

**VIDEO:**
https://user-images.githubusercontent.com/96518669/150334421-e100a21d-cd93-4f19-ab16-fcc3c4d3b2d2.mp4

**EXPECTED:**
The following popup should appear when the user clicks on the apply now button

![image](https://user-images.githubusercontent.com/96518669/150334585-fcd3a308-5647-4d3c-85b8-16d89e638eb0.png)

**Expected image link:**
https://www.figma.com/file/8zldb0Cv4I85beJdBcY1bO/Dashboard-(Free-User)?node-id=622%3A1841

**Comment by siddeshKalangutkar** [comment]
Added fix for toggling the popup on clicking apply now button.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
