### ISSUE TITLE
Offers - filters spacing 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#849]
### **CASE:**
Spacing issues for the offers filters 

### **IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150335055-bb65f592-d742-4fef-9099-a48360c47b05.png)

### **EXPECTED:**
Fix the spacing issues according to the design

### **DESIGN LINK:**
https://www.figma.com/file/8zldb0Cv4I85beJdBcY1bO/Dashboard-(Free-User)?node-id=675%3A2030

**Comment by siddeshKalangutkar** [comment]
Filter alignment has been fixed as per the design. The shared design is of a higher resolution screen. For smaller screen, the filter text will come in 2 lines.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
