### ISSUE TITLE
Footer spacing and links hover function 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#850]
**CASE:**
The footer spacing is wrong and the link are not turning orange on hover 

**IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150336247-9d882082-2a03-42ca-a5ae-16432c0eb958.png)

**EXPECTED:**
The footer spacing should be following:

![image](https://user-images.githubusercontent.com/96518669/150336574-559ff36e-bac0-4fcc-9ac2-57667c5ff197.png)

The privacy policy, FAQ and Terms & Conditions links should turn orange on hover

**Comment by siddeshKalangutkar** [comment]
Footer spacing has been fixed and added hover effect for the links.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
