### ISSUE TITLE
Links aren't functioning & aren't turning orange on hover 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#851]
**CASE:**
The links "Upgrade now" and "Update my information" aren't turning orange on hover

**IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150338495-d339d82a-c847-479b-ac91-cb841b72e679.png)

**EXPECTED:**
The links "Upgrade now" and "Update my information" should turn orange on hover 

**Update my information - popup on clicking the link**
![image](https://user-images.githubusercontent.com/96518669/150340469-0eee4cfc-ba6a-46a0-a509-0a118ee4f140.png)

Upgrade now link - should go to the upgrade now page

**Comment by siddeshKalangutkar** [comment]
Added hover effect to the links.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
