### ISSUE TITLE
Repayment section layout 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#852]
**CASE:**
The layout for Repayment offers section is wrong

**IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150339322-7ed4f2e7-bbf0-4c78-89d7-9c47f61264b0.png)

**EXPECTED DESIGN LAYOUT:**
![image](https://user-images.githubusercontent.com/96518669/150339471-05f727d4-b5b0-4092-be50-ed0020fb4745.png)

The "KNOW MORE" link should turn orange on hover 

**PLEASE CHECK THE SPACING AND LAYOUT FOR THIS SECTION**

**Comment by siddeshKalangutkar** [comment]
The layout has been changed to a slider.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
