### ISSUE TITLE
Offers page functionality issues

### ISSUE THREAD

**Issue by georgioajency** [ajency/CIBIL-CRO#853]
1. Offers details by default should be closed.
2. Compare bar should be sticky towards the bottom.
3. Can compare a max of 3 items. Currently, I can add more than 3.
4. Need minimum of 2 items to compare.
5. I should not be able to compare if only 1 item is selected. Currently, the compare button is disabled when only one item is selected but I can still click on compare. 
6. If the individual offer is expanded and the compare filter is applied, the items that are expanded do not hide
7. Remove option to clear compare. Just compare button. If the user wants to clear compare then they will have to remove all items.
8. If you handling the opening and closing of the accordion, can you also handle inverting of the arrow when the accordion is open/closed.

https://www.awesomescreenshot.com/video/6943507?key=0108c409f4280dfb878169289aabc02d

**Comment by ankitasangodkar** [comment]
**Fixed Issues:**

1. Offers details by default should be closed.
2. Need a minimum of 2 items to compare.
3. I should not be able to compare if only 1 item is selected. Currently, the compare button is disabled when only one item is selected but I can still click on compare.
4. If the individual offer is expanded and the compare filter is applied, the items that are expanded do not hide
5. Remove option to clear compare. Just compare button. If the user wants to clear compare then they will have to remove all items.
6. If you handling the opening and closing of the accordion, can you also handle inverting of the arrow when the accordion is open/closed.
