### ISSUE TITLE
Responsive of the offers page 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#854]
**CASE:**
The design on 4k looks broken

**IMAGE:**
![image](https://user-images.githubusercontent.com/96518669/150342108-9b351d94-b262-42ad-bbe6-2bc248029ec6.png)

**EXPECTED:**
The information on the Offers page should be in the center in the of the page, and not stretched on the page

**Comment by siddeshKalangutkar** [comment]
Content has been aligned in the center.
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers.html
