### ISSUE TITLE
Offers - No information page - desktop & mobile issues 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#858]
Page Link:
https://ajency.github.io/CIBIL-CRO/cibil-dashboard/offers-section.html

### **ISSUES:**

1. The dropdown for "City" changes the height for the page, which should not happen. The dropdown functionality should be similar to that of the "Income Type" field
2. For the "City" field, the text "Country" is written in the textbox. 
3. "Monthly Income Type" field is accepting alphabets also. It should accept only numbers 
4. "Income type" dropdown only has "Self employed" as an input option 
5. Top padding for "You don’t have any offers right now" alerts box is too much. The ideal top & bottom padding should be 20px

### **IMAGES:**

![image](https://user-images.githubusercontent.com/96518669/150727202-b348987f-76eb-47c7-b2f0-75af2bd76050.png)

![image](https://user-images.githubusercontent.com/96518669/150727059-445b9c54-64af-49a0-b239-51dd2a8f3f4c.png)

![image](https://user-images.githubusercontent.com/96518669/150727170-ad9c05d9-e771-481f-9447-b74bf7a74967.png)

![image](https://user-images.githubusercontent.com/96518669/150727285-260a203a-dd7f-4010-b675-af56005eb2e7.png)

**Comment by Saee1799** [comment]
Hi @siddeshKalangutkar 

A few more changes here,

The dropdown for City is different than the dropdown for Income type. Please use the same dropdown for both the fields, preferably the one used for Income type

![image](https://user-images.githubusercontent.com/96518669/150982461-9431a1ed-2aba-4086-9e3d-34280751bcc2.png)


![image](https://user-images.githubusercontent.com/96518669/150982482-e10f0326-6f68-4d03-8030-77181169adbf.png)

**Comment by georgioajency** [comment]
Also the following
![image](https://user-images.githubusercontent.com/43877959/150986328-e9bb3761-209f-404a-92e3-12ba66938899.png)

1. The scroll appears even if there is no value
2. The fields are not equidistant. First is small and other 2 are close to each other
3. Add search icon for city and remove increase/decrease option for amount.
