### ISSUE TITLE
CIBIL Report - employment information tab - desktop

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#864]
Page link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/cibil-report.html

**ISSUES**
1. The line above all the tabs is not required (please remove it from all tabs)
2. Incorrect left spacing for the "Net / gross income indicator" information. It should have a 20px left padding

**IMAGES:**
1.
![image](https://user-images.githubusercontent.com/96518669/150744291-60c15e8e-7f49-4452-966b-2a96583aa436.png)

2.
![image](https://user-images.githubusercontent.com/96518669/150744496-d23b1410-293d-442d-b34e-94a13ce1e196.png)

**Comment by siddeshKalangutkar** [comment]
For point 2, padding-left has been kept as 10px similar to other fields ie. Date reported, Occupation, Income, etc. for maintaining consistency.
