### ISSUE TITLE
shadow effect needed behind cards

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#87]
shadow effect needed behind cards:
web:
![image](https://user-images.githubusercontent.com/4660706/129893517-df698685-3e15-4493-ad93-1b5d309edd1a.png)
design:
![image](https://user-images.githubusercontent.com/4660706/129893551-65692453-6844-4348-8acd-4e8884f781f5.png)

**Comment by chaitanya-ajency** [comment]
Box shadow is already applied.. Gmail not supporting

**Comment by snehaajency** [comment]
seen fr all clients @chaitanya-ajency

**Comment by chaitanya-ajency** [comment]
https://www.campaignmonitor.com/css/box-model/box-shadow/

**Comment by georgioajency** [comment]
Ignore
