### ISSUE TITLE
Offers - mobile view 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#870]
### **ISSUES:**

1. Filter text should be bold
2. Sort filters radio button color should be CIBIL blue 
3. Sort should mention which sorting option is being selected
4. By default, tentative credit limit, high to low option should be selected 
5. On clicking clear filters, the page should not reload, and the default options selected should appear
6. The sort dropdown should be closed by default 
7. Offer details dropdown: the pdf icon is incorrect and the Document icon and "Not available" text should have a spacing of 15px
8. On expanding the offer details, the box border should encompass the details section
9. The number of offers mentioned on the desktop are 4 and in the mobile are 3. Mention 4 offers on the mobile version too

### **IMAGES FOR THE ISSUES RESPECTIVELY:**

1.
![image](https://user-images.githubusercontent.com/96518669/150752621-391f7617-a619-484f-9140-fc9190f7243c.png)

2.
![image](https://user-images.githubusercontent.com/96518669/150752751-ae2751ba-bfb1-4a27-9784-0730eff487d0.png)

3.
![image](https://user-images.githubusercontent.com/96518669/150752873-1a51d7e0-18ca-4b66-86c8-0c01bc43de91.png)

4.
![image](https://user-images.githubusercontent.com/96518669/150753021-99cb9759-df53-45bd-8876-25ba222476c1.png)

5.
![image](https://user-images.githubusercontent.com/96518669/150753059-3b6ee16e-b6a1-4f29-87f4-5a46f4188d05.png)

7.
![image](https://user-images.githubusercontent.com/96518669/150753243-8dfc82a2-9c2d-4446-9a95-7bdab5163a69.png)

8.
![image](https://user-images.githubusercontent.com/96518669/150753653-8ec7548a-c0d7-4544-834d-485a05840a46.png)

9.
![image](https://user-images.githubusercontent.com/96518669/150753916-374cf43c-6a79-4724-9d8b-af4bcb7f2204.png)

**Comment by siddeshKalangutkar** [comment]
Point 3, Not able to refer to an example on how to display the selected sort value.

**Comment by Saee1799** [comment]
Hi @siddeshKalangutkar 

Issues number 3 and 4 have not been resolved.

**Comment by Saee1799** [comment]
example for point 3: when any option is selected by clicking on the radio buttons, the filter name should come on top
![image](https://user-images.githubusercontent.com/96518669/150985179-23a7f62e-476e-4c7d-a9b6-6e01ab03742a.png)

**Comment by siddeshKalangutkar** [comment]
1. Added the sort filter name to the title
2. Kept the above-mentioned option as default
3. Added name filter option
