### ISSUE TITLE
offers page - desktop

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#871]
ISSUES:
1. Number of items mentioned in the personal loans tab is not matching with the number of offers mentioned below in the list 
2. When offer details section is expanded, the line above it should move below it as it is included in the offers section, and the spacing between the documents icon and the text should be 20px
3. The font weight for the texts "Benefits, "Required documents" and "Downloads" in the offer details dropdown should be Intro regular 16px
4. Space between the "Benefits" and the "Required documents" and "Downloads" section should be more (100px in the design)
5. Offer icons should have a left space of 30px
6. Entire section for the offer filters should be clickable 
7. The space between the text "Offer details" and the dropdown arrow should be 6px, and the space should be clickable 
8. The dropdown and up arrows for the offer details text should be center aligned to the text

IMAGES TO THE ISSUES RESPECTIVELY:
1.
![image](https://user-images.githubusercontent.com/96518669/150754259-73388667-7be0-4a35-aa3a-a3d59efb81bf.png)

2.
![image](https://user-images.githubusercontent.com/96518669/150754706-d5b8e219-6b9d-4cb6-92a2-ce5ec9905f5f.png)

4.
![image](https://user-images.githubusercontent.com/96518669/150755310-60dc5269-3d69-45f7-8965-309aba3dcbf0.png)

5.
![image](https://user-images.githubusercontent.com/96518669/150755704-dc58a313-f358-40e6-89f3-1cdbaef5a483.png)

6.
![image](https://user-images.githubusercontent.com/96518669/150755872-f1a60338-f0de-4c33-9ce6-1b3bc38c9ac7.png)

7.
![image](https://user-images.githubusercontent.com/96518669/150756145-1966270c-da7d-4ba6-b163-6e439a7a36cc.png)

8.
![image](https://user-images.githubusercontent.com/96518669/150756328-9dca94f1-e9cf-4dc0-8c86-7cebd80086b3.png)

**Comment by siddeshKalangutkar** [comment]
Unable to achieve point 7 as increasing the button's width increases the box. Requires changing most of the markup for this.

**Comment by Saee1799** [comment]
okay
