### ISSUE TITLE
CIBIL Report - enquiry info tab - mobile 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#875]
ISSUES:
1. on click of show all enquiries, more enquiries need to be shown
2. The upgrade sentence should be on one line only (make this change on all the tabs)

IMAGES:
1.
![image](https://user-images.githubusercontent.com/96518669/150763366-f9a6cd6d-5caf-43fd-a23f-17e3c28f05fd.png)

2.
![image](https://user-images.githubusercontent.com/96518669/150763717-3e8b7167-7c18-4c05-b9bb-4c0e0a610188.png)

2- expected design
![image](https://user-images.githubusercontent.com/96518669/150763834-8c9ed9dd-6ea9-4ca9-8d53-f4899840dc0d.png)

**Comment by siddeshKalangutkar** [comment]
The 2nd point "The upgrade sentence should be on one line only (make this change on all the tabs)" is conflicting with the 3rd point of #861
