### ISSUE TITLE
CIBIL REPORT - DESKTOP (ISSUES IN ALL TABS)

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#879]
### **SUMMARY REPORT TAB:**
1. Content placement and container height issue for the Pricing plans (details given in image number 1). Attaching a link to the figma design for the pricing plans. Please check it out
Figma link: https://www.figma.com/file/8zldb0Cv4I85beJdBcY1bO/Dashboard-(Free-User)?node-id=443%3A201

###**PERSONAL INFORMATION TAB** (Ignore)
1. The gray boxes that display the control number and the raise a dispute button need to have a corner radius of 6px. Please make this change across all tabs that have these boxes

2. The separator lines for the Personal details and identification details should be aligned and one below the other 

### **ACCOUNT INFORMATION TAB** (Ignore)
1. Remove the extra spacing between the "debt" word and the question mark 

### **ENQUIRY INFORMATION TAB**  
1. The entire area around the "Show all enquiries" line is clickable. Only the link should be clickable. The rest of the area should have a cursor, only the link should have an hand icon

### **IMAGES:**

**1. Pricing plan - summary report tab**
![image](https://user-images.githubusercontent.com/96518669/150915297-0b90194d-c669-4f06-846b-54c18c7c89b2.png)

**1. Personal info tab - gray boxes**
![image](https://user-images.githubusercontent.com/96518669/150917171-7ac49c34-8f0b-45fb-a8cc-44c00c589c42.png)

**2. Personal info tab - separator lines**
![image](https://user-images.githubusercontent.com/96518669/150917313-9f07ec7c-fdf0-4b14-a7cd-3b86629082d6.png)

**1. Account information tab**
![image](https://user-images.githubusercontent.com/96518669/150917509-5e634784-6765-40f7-9c4d-2ca3321e7733.png)

**1. Enquiry information tab**
![image](https://user-images.githubusercontent.com/96518669/150917821-d7dea72a-9379-4d5c-89b0-c1048f423f86.png)

**Comment by georgioajency** [comment]
@siddeshKalangutkar - Ignore the points I have added as ignore.
@Saee1799 - Mark this as a separate task but low priority. I do not want to spend too much time on negligible issues.
