### ISSUE TITLE
Dashboard screen issues - iPad resolution 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#881]
### **ISSUES:**

1. The user information cards are not of the same height and the question mark for the new score score sim animation is not aligned
2. Text is broken in the CIBIL Alerts card
3. The feature boxes in the Unlock more features with the CIBIL subscription container are not of the same size 
4. Repayment offer boxes are not of the same height 
5. All the text in the Personalized offers can fit in the same line. Also the number of offers available should be center aligned to the container

### **IMAGES:**

1. 
![image](https://user-images.githubusercontent.com/96518669/150943366-a379d749-b993-41a2-90e4-d60cee9a5c59.png)

2.
![image](https://user-images.githubusercontent.com/96518669/150943611-33d5444e-017a-4630-a684-155cbcafa461.png)

3.
![image](https://user-images.githubusercontent.com/96518669/150943810-c7e0cc86-53db-428e-928a-4fd1c50faab7.png)

4.
![image](https://user-images.githubusercontent.com/96518669/150943974-f5599e87-6eb9-43ba-96dd-f973099d5378.png)

5.
![image](https://user-images.githubusercontent.com/96518669/150944264-81d94a99-9ebc-454e-ac6a-9c9877c03350.png)

**Comment by siddeshKalangutkar** [comment]
Preview link: https://ajency.github.io/CIBIL-CRO/cibil-dashboard/dashboard.html
