### ISSUE TITLE
Dashboard cards - Issues

### ISSUE THREAD

**Issue by georgioajency** [ajency/CIBIL-CRO#885]
1. Reduce the speed of gauge on load. The pointer moves too fast.

2. The 600 score card, the needle looks pixelated
![image](https://user-images.githubusercontent.com/43877959/151554571-05f79094-9809-4f9e-a3dd-6a6427f49d71.png)

3. On click of Refresh now, the 6th card should show up. More like how you did for Score Sim card for the dashboard.

4. This text should not be clickable
![image](https://user-images.githubusercontent.com/43877959/151554405-6749801d-3ff2-46ae-b0c9-be45c679b8dc.png)

5. Rename this button to "Yearly Refresh"
![image](https://user-images.githubusercontent.com/43877959/151554479-65043969-2999-49ee-a877-d0fa5bbf8a8e.png)

**Comment by siddeshKalangutkar** [comment]
Point 2 is not achievable as no CSS changes can be made to the gauge as it comes from the gauage.js library

**Comment by georgioajency** [comment]
When the delay is there, nothing is shown. Can the gaugue be shown but starting at 0 and once the page is loaded the animation starts?
![image](https://user-images.githubusercontent.com/43877959/151737250-781d6100-2e38-46c4-84ec-7f6da8f45ef0.png)
 Also can we lower the animation speed down even further?

**Comment by siddeshKalangutkar** [comment]
Passing 2 values to gauge is not possible, hence I have removed the delay and made the animation slower.
