### ISSUE TITLE
Ui issues noticed

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#9]
**case**:

1.  the vertical line height is more 
![image](https://user-images.githubusercontent.com/4660706/122526160-a41bdc00-d037-11eb-8609-4733013af373.png)

2. the color of 'get started' is wrong,should be ffffff
![image](https://user-images.githubusercontent.com/4660706/122526410-e47b5a00-d037-11eb-94e0-9a10ea12c834.png)

![image](https://user-images.githubusercontent.com/4660706/122527585-12ad6980-d039-11eb-8b34-fa0d984f4b23.png)
![image](https://user-images.githubusercontent.com/4660706/122527959-72a41000-d039-11eb-970a-2405637ad987.png)

3. the right arrow is getting cropped 
![image](https://user-images.githubusercontent.com/4660706/122527702-3375bf00-d039-11eb-87aa-bb819b551be6.png)

**Comment by Vaibhavarolkar** [comment]
point 3 - Cannot replicate the issue

**Comment by snehaajency** [comment]
fixed
