### ISSUE TITLE
Be Worthy - CTA text 

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#900]
1. CTA text is incorrect. The text should be "Get FREE CIBIL SCORE" 
![image](https://user-images.githubusercontent.com/96518669/159216045-9ef8e8f3-f5f1-4729-9399-39354ed148a8.png)

**Comment by georgioajency** [comment]
@Saee1799 This is correct. The text was updated by client. 

Closing the ticket
