### ISSUE TITLE
#BeWorthy text color

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#905]
The text color for #BeWorthy is incorrect. The color for the hashtag and the word "be" is black (#202020) and the text "Worthy" has the CIBIL blue color (#00A6CA)
![image](https://user-images.githubusercontent.com/96518669/159221031-735adc26-f91e-48e0-9f1e-a75f46a948f6.png)

![image](https://user-images.githubusercontent.com/96518669/159221088-866e2f03-6f6d-49d4-a3ac-df821c289269.png)

**Comment by georgioajency** [comment]
Client requested to keep it full blue
