### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#906]
The icon for "Learn how to improve your score" is different in the design. 

The one used on the Developed website 
![image](https://user-images.githubusercontent.com/96518669/159221264-fadf5dc5-1258-4ebd-9c66-66e691fc3c5f.png)

The one on the figma design
![image](https://user-images.githubusercontent.com/96518669/159221323-c84d5129-f670-4061-b6d6-0401773f43ec.png)

**Comment by georgioajency** [comment]
In design is old. On website is latest

**Comment by Saee1799** [comment]
okay @georgioajency
