### ISSUE TITLE
Font family issue - subscription box

### ISSUE THREAD

**Issue by Saee1799** [ajency/CIBIL-CRO#913]
The font for the text "Everything you need to be credit-ready. Learn. Plan. Protect. All in one place." is incorrect. It should be Intro regular, 16px. 
![image](https://user-images.githubusercontent.com/96518669/162884021-8e8d97aa-e055-4606-b3c9-b1f0f4ca0ea5.png)

**Comment by georgioajency** [comment]
Seems correct
