### ISSUE TITLE
D_CIBIL Homepage (Multilingual ) _ Bengali : Text Issue

### ISSUE THREAD

**Issue by saieshv** [ajency/CIBIL-CRO#920]
1. This is to be kept in a single line , 
(Heading text below the Hero section)
<img width="1059" alt="Screenshot 2022-11-04 at 1 08 14 PM" src="https://user-images.githubusercontent.com/81156455/199918578-1368c089-0f73-401a-a38b-26f8b929e249.png">

**Comment by siddeshKalangutkar** [comment]
For different screen sizes, languages, and os the width of the element will change and hence the text will come on the next line.
