### ISSUE TITLE
M_CIBIL Homepage (Multilingual ) _ Heading Issue 

### ISSUE THREAD

**Issue by saieshv** [ajency/CIBIL-CRO#922]
All the headings (section titles) are to be kept bold on mobile 
1. 
<img width="323" alt="Screenshot 2022-11-04 at 1 44 21 PM" src="https://user-images.githubusercontent.com/81156455/199924872-8daf9711-700e-4cd5-add0-a3886da75123.png">

_______________________________________________________________________

2. 
<img width="325" alt="Screenshot 2022-11-04 at 1 45 05 PM" src="https://user-images.githubusercontent.com/81156455/199924994-5b142312-16c8-4684-a0dd-21bd2efd2904.png">

_______________________________________________________________________

3. 
<img width="321" alt="Screenshot 2022-11-04 at 1 46 00 PM" src="https://user-images.githubusercontent.com/81156455/199925172-f857a9f4-31de-461a-b54d-41752aff8ab9.png">

_______________________________________________________________________

**Comment by saieshv** [comment]
Note: To be applied on all pages

**Comment by siddeshKalangutkar** [comment]
Font weight appears correctly (bold) on mobile devices.
