### ISSUE TITLE
D_ Tabs Issue

### ISSUE THREAD

**Issue by saieshv** [ajency/CIBIL-CRO#924]
There is small x-axis shift in the content when clicking on the last tab 
maybe because of scroll bar of the site on the right.

Ref. Video 

https://user-images.githubusercontent.com/81156455/209318350-8b46a094-7eb0-43a1-b225-3eda26c44cbb.mov

**Comment by siddeshKalangutkar** [comment]
@saieshv  The shift is because of the content. If the content is less than the viewport height, the scrollbar of the browser disappears. 
When integrated into the live page, this issue won't occur as there will be a header and footer

**Comment by saieshv** [comment]
Okay sure
