### ISSUE TITLE
D_ Pop-Up Trigger Issue 

### ISSUE THREAD

**Issue by saieshv** [ajency/CIBIL-CRO#926]
Sometimes on clicking the checkboxes from "Loans Type" (Pre-Qualified, In-Principle Loans)
the Pop-up sometimes gets triggered 

Ref. Video
 

https://user-images.githubusercontent.com/81156455/209321614-96dcdeee-e080-46b5-afb8-fb967d059a9c.mov

**Comment by siddeshKalangutkar** [comment]
@saieshv  The popup appears on hovering the info icon (This was the new requirement)

**Comment by saieshv** [comment]
https://user-images.githubusercontent.com/81156455/209322442-610561e1-b0ee-4404-aae3-1c4d8828ac27.mov

Note : 
If the user is causally browsing, or accidentally moved his mouse over the icons, these pop-ups will be triggered. 
he will have no idea why it happened. The user might feel some functionality from the CIBIL side is broken. 

@ekta do check this and let us know if we can make the trigger "On-Click"

**Comment by saieshv** [comment]
Change Requested by Client
