### ISSUE TITLE
icon beside "Would my CIBIL Score be affected if I checked it?" looks small on mobile devices.

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#98]
icon beside "Would my CIBIL Score be affected if I checked it?" looks small on mobile devices.
![image](https://user-images.githubusercontent.com/4660706/129899289-c3ebd2c2-e56b-422b-a8cc-285c090bbd5b.png)

**Comment by chaitanya-ajency** [comment]
Kept it to achieve responsive design
