### ISSUE TITLE
Button text is wrong

### ISSUE THREAD

**Issue by snehaajency** [ajency/CIBIL-CRO#99]
Button text is wrong
web:
![image](https://user-images.githubusercontent.com/4660706/130018273-27b0de7c-2510-415f-adfb-1a6492bd8a62.png)

design:
![image](https://user-images.githubusercontent.com/4660706/130018290-21cb31b2-5b30-48e4-850a-66a875130f07.png)

**Comment by georgioajency** [comment]
@chaitanya-ajency 
Mail 1 has Login to Subscribe
Mail 2 has Login to Upgrade
